### ISSUE TITLE
Assets need to be included in a higher rendition

### ISSUE THREAD

**Issue by LucaNerlich** [aemsites/audi#19]
At the moment, **all** image assets in Word are of low quality. We need to re-import them.

Lossy
https://main--audi--aemsites.hlx.page/uk/web/en/media_10c603fd0642972f978d2c84bad19cd93204df9c5.jpeg?width=2000&format=webply&optimize=medium

Lossless
https://main--audi--aemsites.hlx.page/uk/web/en/media_10c603fd0642972f978d2c84bad19cd93204df9c5.jpeg?width=2000&format=webpll&optimize=medium

**Comment by amol-anand** [comment]
Just get the original images when you re author the pages. it was already imported and the images you see are what the import gets automatically. Since we only have a few pages, doesn't make sense doing any work on the importer as such for this.

**Comment by kunwarsaluja** [comment]
Done
