### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by amol-anand** [aemsites/audi#2]
### **Header**

**Desktop**
![Screenshot 2024-03-01 at 2 49 54 PM](https://github.com/aemsites/audi/assets/7074782/2eb1fafe-735c-406f-80c3-dd5ac63c46fd)

![Screenshot 2024-03-01 at 2 49 41 PM](https://github.com/aemsites/audi/assets/7074782/e23d67ad-6fa7-4ca1-840b-42558833a425)

**Mobile**
![Screenshot 2024-03-01 at 2 54 24 PM](https://github.com/aemsites/audi/assets/7074782/6e01ad71-42d2-49f1-838d-5b779962fb3e)

![Screenshot 2024-03-01 at 2 54 31 PM](https://github.com/aemsites/audi/assets/7074782/caae2911-5c73-45a7-b5b5-20c7759d7082)

**Dev Notes:**
1. We can get the original json from the current site and build the header based on that so that it will reflect any changes to the original header that is across the whole site.
2. Plan is to NOT use the existing micro frontend react app that the current header is built on
3. For Search, we can just call the same API the current micro frontend is calling and display the results from the header itself.

**Comment by LucaNerlich** [comment]
done via #15
