### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by amol-anand** [aemsites/audi#3]
**Mobile**
![Screenshot 2024-03-01 at 2 55 57 PM](https://github.com/aemsites/audi/assets/7074782/83f04376-aa7b-4f08-9f09-bc2f817c4229)

**Desktop**
![Screenshot 2024-03-01 at 2 56 12 PM](https://github.com/aemsites/audi/assets/7074782/b6ef401b-e656-4ea2-9bc5-206470d30661)

**Dev Notes:**
Get the current footer json from existing location (fallback to a json in our codebase) and built the footer from there so that any changes to the footer across the site will still reflect in this section as well.

**Comment by LucaNerlich** [comment]
[footer.json](https://github.com/aemsites/audi/files/14510090/footer.json)

The json keys match pretty directly to the content:
![image](https://github.com/aemsites/audi/assets/5942270/e338de3c-5107-4067-95d0-79ced832c44d)

json includes an empty `LanguageLinks[]` array which we can ignore.
