### ISSUE TITLE
Stickyness of subnavigation

### ISSUE THREAD

**Issue by markusbulla** [aemsites/audi#55]
The subnavigation (#5) should be sticky when the user scrolls through the page: 

![Screenshot 2024-03-13 at 16 44 52](https://github.com/aemsites/audi/assets/34375428/8adef395-e777-4865-8bd3-1f0ccde616e8)

![Screenshot 2024-03-13 at 16 44 39](https://github.com/aemsites/audi/assets/34375428/4313c716-452d-42ee-b51c-14e76975cecf)

![Screenshot 2024-03-13 at 16 44 17](https://github.com/aemsites/audi/assets/34375428/b3c636d4-1435-4696-9f30-453059aa1c3f)

**Comment by LucaNerlich** [comment]
The subnav is (now?) contained in a `section hero-container subnav-container` div, which stops the subnav from sticking to the page top on scroll.

**Comment by LucaNerlich** [comment]
fixed with dd452c58242525bfaac6a7a23fbb64d72d61eef6
