### ISSUE TITLE
Hero - Text Top and bottom Alignment

### ISSUE THREAD

**Issue by LucaNerlich** [aemsites/audi#56]
Used-Cars - bottom aligned
![image](https://github.com/aemsites/audi/assets/5942270/72da3c43-52ff-45d9-8468-3169a5120606)

Other Pages - top aligned
![image](https://github.com/aemsites/audi/assets/5942270/a81add9f-555e-4b96-8baa-4390cce8fd6a)

**Comment by amol-anand** [comment]
Adding a bottom variation should help with this. Default can be top. should only be css differences
