### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by LucaNerlich** [aemsites/audi#7]
List of Cards with Links (Can be 2 or 3 wide as shown on screenshots)

**Desktop:**
![image](https://github.com/aemsites/audi/assets/5942270/4bca2ad3-467f-4e1e-b3b4-a4d6c30bdd90)

![Screenshot 2024-03-04 at 6 04 12 PM](https://github.com/aemsites/audi/assets/7074782/6a361477-cc74-4fd6-9962-546aa1599293)

**Mobile:**
![Screenshot 2024-03-04 at 6 04 38 PM](https://github.com/aemsites/audi/assets/7074782/af9a6615-b091-40e9-8a98-a411456ee40d)

**Comment by amol-anand** [comment]
updated the description with a 2 card wide variation in addition to 3 card wide
